apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite
  template:
    metadata:
      labels:
        app: sqlite
    spec:
      containers:
      - name: sqlite3
        image: db_deployment:latest
        envFrom:
        - configMapRef:
            name: sqlite-env
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: sqlite3-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: sqlite3-pv
        persistentVolumeClaim:
          claimName: sqlite3-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlite
spec:
  selector:
    app: sqlite
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
